import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">FrameSixtyTwo</Link>
        </li>
        <li>
          <Link to="/haveli">Haveli</Link>
        </li>
        <li>
          <Link to="/junoon">Junoon</Link>
        </li>
        <li>
          <Link to="/qabail">Qabail</Link>
        </li>
        <li>
          <Link to="/saltnpeper">Saltnpeper</Link>
        </li>
        <li>
          <Link to="/butt">Butt</Link>
        </li>
        <li>
          <Link to="/restaurant">Restaurant</Link>
        </li>
        <li>
          <Link to="/monal">Monal</Link>
        </li>
        <li>
          <Link to="/gallery">Gallery</Link>
        </li>
        <li>
          <Link to="/login">Login</Link>
        </li>
        <li>
          <Link to="/andaaz">Andaaz</Link>
        </li>
        <li>
          <Link to="/spice">Spice</Link>
        </li>
        <li>
          <Link to="/dynasty">Dynasty</Link>
        </li>
        <li>
          <Link to="/tuscany">Tuscany</Link>
        </li>
        <li>
          <Link to="/dumpukht">Dumpukht</Link>
        </li>
        <li>
          <Link to="/signup">SignUp</Link>
        </li>
        <li>
          <Link to="/khaabe">Khaabe</Link>
        </li>
        <li>
          <Link to="/contactus">ContactUs</Link>
        </li>
        <li>
          <Link to="/yum">Yum</Link>
        </li>
        <li>
          <Link to="/kahanifour">KahaniFour</Link>
        </li>
        <li>
          <Link to="/actvities">Actvities</Link>
        </li>
        <li>
          <Link to="/maps">Maps</Link>
        </li>
        <li>
          <Link to="/cafes">Cafes</Link>
        </li>
        <li>
          <Link to="/urban">Urban</Link>
        </li>
        <li>
          <Link to="/gloria">Gloria</Link>
        </li>
        <li>
          <Link to="/jade">Jade</Link>
        </li>
        <li>
          <Link to="/mocca">Mocca</Link>
        </li>
        <li>
          <Link to="/costa">Costa</Link>
        </li>
        <li>
          <Link to="/buttler">Buttler</Link>
        </li>
        <li>
          <Link to="/cinnabon">Cinnabon</Link>
        </li>
        <li>
          <Link to="/karak">Karak</Link>
        </li>
        <li>
          <Link to="/homepage">Homepage</Link>
        </li>
        <li>
          <Link to="/legalpolicy">LegalPolicy</Link>
        </li>
        <li>
          <Link to="/shop">Shop</Link>
        </li>
        <li>
          <Link to="/arcadian">Arcadian</Link>
        </li>
        <li>
          <Link to="/kahanione">KahaniOne</Link>
        </li>
        <li>
          <Link to="/kahanitwo">KahaniTwo</Link>
        </li>
        <li>
          <Link to="/framesixtysix">FrameSixtySix</Link>
        </li>
        <li>
          <Link to="/kahanithree">KahaniThree</Link>
        </li>
        <li>
          <Link to="/kahani">Kahani</Link>
        </li>
        <li>
          <Link to="/kahanifive">KahaniFive</Link>
        </li>
        <li>
          <Link to="/events">Events</Link>
        </li>
        <li>
          <Link to="/reviews">Reviews</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
